### ISSUE TITLE
is it possible to use multiple bounding box using Inceptionv3 model?

### ISSUE THREAD

**Issue by steve21124** [hollance/YOLO-CoreML-MPSNNGraph#1]
Yolo has grid method but InceptionV3 does not. 
MLMultiArray
`
class TinyYOLOOutput : MLFeatureProvider {
    let grid: MLMultiArray
    
    var featureNames: Set<String> {
        get {
            return ["grid"]
        }
    }
    
    func featureValue(for featureName: String) -> MLFeatureValue? {
        if (featureName == "grid") {
            return MLFeatureValue(multiArray: grid)
        }
        return nil
    }
    
    init(grid: MLMultiArray) {
        self.grid = grid
    }
}
`

**Comment by hollance** [comment]
You might be able to train Inception-v3 the same way as YOLO (see the YOLO paper).

**Comment by steve21124** [comment]
Thanks. wil check it out. so it seems like, it is possible to do
