### ISSUE TITLE
Will vision Framework able to identify the same object that it identify earlier?

### ISSUE THREAD

**Issue by steve21124** [hollance/YOLO-CoreML-MPSNNGraph#11]
For example, Vision found a honda car with blue color. Is it able to identify the same car that it previously "track" 3 minutes later? or the tracking is release from memory once it is out of the capture area. Basically, I want to know if a new car coming in, if it is the same car that it is previously track?

**Comment by hollance** [comment]
The answer is probably no but I haven't used Vision tracking. As for YOLO, it does not do tracking at all.

**Comment by steve21124** [comment]
Thank you for the info. Yes. not out of the box
