### ISSUE TITLE
Lower input sizes issues

### ISSUE THREAD

**Issue by anonym24** [hollance/YOLO-CoreML-MPSNNGraph#21]
```
  public static let inputWidth = 416
  public static let inputHeight = 416
```

I tried to set smaller values

```
  public static let inputWidth = 256
  public static let inputHeight = 256
```

but the rects aren't drawn correctly

**Comment by hollance** [comment]
The input size is 416x416 because it gets scaled down 5 times to be 13x13. If you set the input to 256x256 and scale it down 5 times the final grid becomes 8x8, and so you'll have to adjust the code that computes the bounding boxes for that too. (But I'm not sure how well this will actually work...)

**Comment by anonym24** [comment]
of course accuracy become much worse but it should process faster

could please tell me on which devices did you tested this project and how fast it works, iPhone 7, 8 or even X?

I had time to test only on old iPad mini 2 (2 core, 1.3 GHz) :)

**Comment by anonym24** [comment]
also would be great to implement Tensorflow object model (ssd_mobilenet_v1_coco) for CoreMl

https://github.com/tensorflow/models/tree/master/research/object_detection
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

There is already a project to run Tensorflow object detection model on iOS, but it works with Tensorflow 
https://github.com/JieHe96/iOS_Tensorflow_ObjectDetection_Example

**Comment by hollance** [comment]
I think this gets about 10 FPS on the iPhone 7. I haven't tried on 8 or X. However, I did implement MobileNet+SSD (for a client, so I cannot share the code) and it gets 30 FPS on iPhone 7. So it's a lot faster than Tiny YOLO, and I think it's similar in accuracy.

**Comment by anonym24** [comment]
wow results sounds great:) 
yeah I understand you can't  share it 

thanks for answers
