### ISSUE TITLE
Boxes remain on screen after moving on from objects

### ISSUE THREAD

**Issue by vvkv** [hollance/YOLO-CoreML-MPSNNGraph#24]
Thank you so much for your work here. I have began to notice the issue of bounding boxes persisting on my iphone 6s screen even after I point to another object. I am using my own ML model that I converted from custom training with darknet, I have using this model for a few days now and today is the first time this issue has come up. I reinstalled the app with my coreML graph on with no real luck yet. Any pointers as to why this might be? 
The app is running at about 11 FPS so its clearly not an obvious lag. Any guidance will be very helpful. Thanks

**Comment by hollance** [comment]
When the app gets the results from YOLO, it always reuses the old bounding boxes and then makes the remaining ones invisible. Perhaps something is wrong there? If you can reproduce the issue then that would be the first thing I'd look at.
