### ISSUE TITLE
increase numbers of label

### ISSUE THREAD

**Issue by steve21124** [hollance/YOLO-CoreML-MPSNNGraph#3]
Currently, I think the number of label is limited to 20 (in helper.swift) is it?

I tested it out with yolo9000 and it still limit only to above 20 array. How to increase the number of label to more than 20?

**Comment by hollance** [comment]
The version used in this app is trained on the PASCAL VOC dataset, which only has 20 classes. I think there is also a version trained on COCO that has more classes.

**Comment by steve21124** [comment]
Thank you, I am able to generate it now. It take a while from basic of knowing nothing to get to know  yolo.
