### ISSUE TITLE
FPS on ipad or ipad pro

### ISSUE THREAD

**Issue by LeeroyHannigan** [hollance/YOLO-CoreML-MPSNNGraph#30]
Hi, 
I'm not sure if this is the correct place for questions to be asked, apologies if not. I am designing an app that would require Yolo to run at, or close to the same frame rate as video. Would this solution get anywhere close to 30fps on Ipad or Ipad pro?

Thanks

**Comment by hollance** [comment]
Probably not. I don't remember what sort of FPS this gets on an iPad but YOLO is slower than the alternative, SSD (on MobileNet).
