### ISSUE TITLE
FPS go down when app runs a few minutes

### ISSUE THREAD

**Issue by haemi** [hollance/YOLO-CoreML-MPSNNGraph#31]
on my iPhone X, the FPS from the demo app (coreml) starts at around 22/23 fps but goes down slowly but steadily - after ~ 2 minutes to about 13 fps - without moving the phone, just laying on the table.

**Comment by hollance** [comment]
How hot is the phone at that point? The GPU will automatically throttle down when it gets too warm.

**Comment by haemi** [comment]
it is hot, so that would explain that. Ich guess that cant be avoided?
