### ISSUE TITLE
I would like to improve detection performance

### ISSUE THREAD

**Issue by JGProg** [hollance/YOLO-CoreML-MPSNNGraph#33]
Hi guys,

I use Yolo for localization object on image. But when a person is on the side Yolo don't detect as a person.. 
No detection.. how to perform that ?

The version of Yolo use is V1 ? How to use the new version fo Yolo (V3) ?

Thank you for your answer.

**Comment by hollance** [comment]
The version of YOLO used is v2 but only the "tiny" variant not the full one.

**Comment by JGProg** [comment]
Thank you for your answer !

You can help me why Yolo don't detect a person is on the side ?  You have an idea ? 
Can it be that I use it with photo processing instead of video?

**Comment by hollance** [comment]
Do you have an example picture?

**Comment by JGProg** [comment]
Yes, this picture for example.

![182773387](https://user-images.githubusercontent.com/1257401/39047108-00821546-4499-11e8-9426-5049ebafcfb7.jpg)

**Comment by hollance** [comment]
I'm not sure this version of YOLO was trained on humans that are only partially visible. If you want these kinds of photos to be recognized as a person you'll probably need to train the model yourself on suitable data.

**Comment by JGProg** [comment]
Ok thank you very much !
