### ISSUE TITLE
Support for yolo v3

### ISSUE THREAD

**Issue by chinmay5** [hollance/YOLO-CoreML-MPSNNGraph#36]
Is there some effort in pipeline for conversion to YOLO v3?

**Comment by hollance** [comment]
Not from me. ;-) YOLO is generally a lot slower than SSD(Lite) and so I'm not really in a hurry to convert it to iOS.

**Comment by chinmay5** [comment]
I was wondering if things need to be done for tiny-yolo part. The v3 is fast even for tiny-yolo and was wondering if conversion can be tried

**Comment by chinmay5** [comment]
Can you help me a bit. I started converting tiny-yolov3 and although the Keras conversion looks good, it failed when I tried converting it to coreml
![image](https://user-images.githubusercontent.com/16525717/40585267-fae38d20-61af-11e8-8003-863b59c70882.png)

I am not sure what exactly is the reason for the error. I would really appreciate your help

**Comment by hollance** [comment]
Are you sure input1 is an image input?

**Comment by chinmay5** [comment]
I just followed the steps outlined. I am not sure how to check it. Can you please help

**Comment by hollance** [comment]
I'm afraid I don't have the time...
