### ISSUE TITLE
Understanding the computation with anchor boxes

### ISSUE THREAD

**Issue by chinmay5** [hollance/YOLO-CoreML-MPSNNGraph#37]
Hi, I am not able to understand how the computation for the bounding boxes along with the anchors are happening.
`let w = exp(tw) * anchors[2*b    ] * blockSize
 let h = exp(th) * anchors[2*b + 1] * blockSize`
[Helper.swift](https://github.com/hollance/YOLO-CoreML-MPSNNGraph/blob/a1241f3cf1fd155039c45ad4f681bb5f22897654/TinyYOLO-CoreML/TinyYOLO-CoreML/Helpers.swift#L79)

1. How were these anchor boxes selected ?
2. What was the reason to multiply with the exponential function before scaling with the anchor box value?
The second part is what I am more intrigued by. Any help would be highly appreciated.

**Comment by hollance** [comment]
I'm actually putting the finishing touches on a blog post that explains all this. :-)

**Comment by chinmay5** [comment]
Please post the link here as well once you are done :)

**Comment by hollance** [comment]
All right, here it is: http://machinethink.net/blog/object-detection/
