### ISSUE TITLE
Reduced FPS

### ISSUE THREAD

**Issue by itsayush** [hollance/YOLO-CoreML-MPSNNGraph#4]
Thanks for much for doing this. I tried out the CoreML version of this and noticed that FPS for prediction is lower than what it used to be with bare bone MPS [using your Forge project]. Would you know why that might be the case ?

**Comment by hollance** [comment]
I think they are about the same now. What sort of FPS are you getting and on what device?

**Comment by itsayush** [comment]
I am getting around 4.5 FPS on  iPhone 7. You Forge example was giving ~9 FPS on iPhone 6s. So definitely it has taken a hit.

**Comment by 0xPr0xy** [comment]
Averaging ~7 FPS and ~0.13 seconds/prediction on iphone 7 running iOS 11, using the CoreML project from this repository without modifications
