### ISSUE TITLE
Performance decrease

### ISSUE THREAD

**Issue by ductus** [hollance/YOLO-CoreML-MPSNNGraph#60]
Hello,
I run TinyYOLO-CoreML on my iPhone X (iOS 12.4), I put my iPhone on the table, do not detect anything.
After about 5 minutes:
+ Elapsed increases from 0.1 to 0.56 second
+ FPS reduces from 24 to 5

I have same problem when I detect person.
Is it a bug? How can I keep performance well after run a long time?

Thank you!

**Comment by hollance** [comment]
How hot is your phone at this point? If it's hot, then the GPU has throttled down to prevent the phone from overheating.

**Comment by ductus** [comment]
Yes, my phone is hot. I want to open the app for a long time, how should I do?

**Comment by hollance** [comment]
If you want to run this kind of model for a long time, you should run it less often. Running at full speed is only a good idea if it's for short periods of time.

I'd also suggest using a different architecture, such as MobileNet2+SSDLite, which runs much more efficiently on older phones such as the iPhone X.

**Comment by ductus** [comment]
Thank you very much.
