### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'concat_v2'

### ISSUE THREAD

**Issue by kaublezw** [hollance/YOLO-CoreML-MPSNNGraph#65]
Trying to convert a Tiny Yolo v4 model to Kiras using a Google Colab environment and getting the following error: AttributeError: module 'tensorflow' has no attribute 'concat_v2' 

Ran this command: 
!python3 yad2k.py -p ../yolov4-tiny-custom.cfg ../yolov4-tiny-custom_best.weights model_data/tiny-yolo-voc.h5

**Comment by hollance** [comment]
This is not the right place to ask that question. This repo only supports TinyYOLOv2, and the old versions of Keras and TF. Perhaps you can ask in the YAD2K project.
