### ISSUE TITLE
Generated coreml file crash on loading

### ISSUE THREAD

**Issue by fsmanji** [hollance/YOLO-CoreML-MPSNNGraph#9]
Hi, first of all thank you for providing such an amazing project.
I've tried your demo it works great.
When I tried to generate a new model following the steps and with the original .cfg and .weights file, everything works great, however when I try to load the generated yolo class from YOLO.swift, the app crashed everytime, could you help me if there's anything that I messed up ?
I'm following the steps in readme. 
Great thanks.

here is the screenshot:
<img width="1145" alt="screen shot 2017-08-02 at 11 53 44 pm" src="https://user-images.githubusercontent.com/8003160/28909665-3bb8a658-77de-11e7-8e21-5f2de1fedce9.png">

**Comment by fsmanji** [comment]
More info: iOS 11 beta4, Xcode 9 beta3

**Comment by hollance** [comment]
That error message does not contain a lot of useful info. However, the first thing I'd try is updating Xcode to beta 4.

**Comment by fsmanji** [comment]
Thanks for quick reply @hollance !
I've tried that as well, but it doesn't help.
I've found the issue, it's the problem with the tools versions. tensorflow 1.2.x + Keras 1.2.2 doesn't seemed to cause the issue.
